###

GET http://localhost:3000/usuarios

###

POST http://localhost:3000/usuarios
Content-Type: application/json

{
    "nome": "GAIRO",
    "email": "nicolas@gmail",
    "senha": "12345"
}

###

PUT http://localhost:3000/usuarios/3
Content-Type: application/json

{
    "nome": "GAIRO",
     "email": "nicolas@gmail",
    "senha": "12345"
}

###

DELETE http://localhost:3000/usuarios/2


###

POST http://localhost:3000/login
Content-Type: application/json

{
    
    "email": "nicoOOOOOlas@gmail",
    "senha": "12345"
}
